// Code generated by "stringer -type=Type"; DO NOT EDIT.

package note

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[None-0]
	_ = x[Header-1]
	_ = x[PrefixInline-2]
	_ = x[Prefix-3]
	_ = x[SuffixInline-4]
	_ = x[Suffix-5]
	_ = x[Footer-6]
}

const _Type_name = "NoneHeaderPrefixInlinePrefixSuffixInlineSuffixFooter"

var _Type_index = [...]uint8{0, 4, 10, 22, 28, 40, 46, 52}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
