// Code generated by "stringer -type=lineType"; DO NOT EDIT.

package charmed

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[lineText-0]
	_ = x[lineClose-1]
}

const _lineType_name = "lineTextlineClose"

var _lineType_index = [...]uint8{0, 8, 17}

func (i lineType) String() string {
	if i < 0 || i >= lineType(len(_lineType_index)-1) {
		return "lineType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _lineType_name[_lineType_index[i]:_lineType_index[i+1]]
}
