// Code generated by "stringer -type=blockStage"; DO NOT EDIT.

package notes

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[emptyStage-0]
	_ = x[startingStage-1]
	_ = x[headerStage-2]
	_ = x[subheaderStage-3]
	_ = x[paddingStage-4]
	_ = x[bufferStage-5]
	_ = x[inlineStage-6]
	_ = x[footerStage-7]
}

const _blockStage_name = "emptyStagestartingStageheaderStagesubheaderStagepaddingStagebufferStageinlineStagefooterStage"

var _blockStage_index = [...]uint8{0, 10, 23, 34, 48, 60, 71, 82, 93}

func (i blockStage) String() string {
	if i < 0 || i >= blockStage(len(_blockStage_index)-1) {
		return "blockStage(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _blockStage_name[_blockStage_index[i]:_blockStage_index[i+1]]
}
